package(default_visibility = ["//visibility:public"])
py_library(
  name = "transform",
  srcs = [
    "transform.py"
  ]
)


py_library(
  name = "file_handler",
  srcs = [
    "file_handler.py"
  ]
)